// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03iqPtJwOxU_oSsEW7pdRDKMx8cxCFGo',
    appId: '1:227998590918:web:03d46b662cc29291ea74c7',
    messagingSenderId: '227998590918',
    projectId: 'uth-smarttasks-5cfe0',
    authDomain: 'uth-smarttasks-5cfe0.firebaseapp.com',
    storageBucket: 'uth-smarttasks-5cfe0.firebasestorage.app',
    measurementId: 'G-GHTR6E772C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuGtpePnTB8WngZGCuwjzoQpauEuvP31o',
    appId: '1:227998590918:android:3cf36ca1b775792fea74c7',
    messagingSenderId: '227998590918',
    projectId: 'uth-smarttasks-5cfe0',
    storageBucket: 'uth-smarttasks-5cfe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqaJN7sCQV89ZQ0bhabxOtNdw70P2fktk',
    appId: '1:227998590918:ios:0eda0d50995e80c6ea74c7',
    messagingSenderId: '227998590918',
    projectId: 'uth-smarttasks-5cfe0',
    storageBucket: 'uth-smarttasks-5cfe0.firebasestorage.app',
    iosBundleId: 'com.example.uthSmarttasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqaJN7sCQV89ZQ0bhabxOtNdw70P2fktk',
    appId: '1:227998590918:ios:0eda0d50995e80c6ea74c7',
    messagingSenderId: '227998590918',
    projectId: 'uth-smarttasks-5cfe0',
    storageBucket: 'uth-smarttasks-5cfe0.firebasestorage.app',
    iosBundleId: 'com.example.uthSmarttasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD03iqPtJwOxU_oSsEW7pdRDKMx8cxCFGo',
    appId: '1:227998590918:web:334af5c65170fdd6ea74c7',
    messagingSenderId: '227998590918',
    projectId: 'uth-smarttasks-5cfe0',
    authDomain: 'uth-smarttasks-5cfe0.firebaseapp.com',
    storageBucket: 'uth-smarttasks-5cfe0.firebasestorage.app',
    measurementId: 'G-372TSS37KL',
  );
}
